name: 'Docker Release'

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/**'
jobs:
    build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=true
            type=raw,value=${{ steps.tag.outputs.tag }},enable=true
            type=raw,value=${{ steps.tag.outputs.sha }},enable=true
            type=raw,value=${{ steps.tag.outputs.short_sha }},enable=true
          flavor: latest=false

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TAG=${{ steps.tag.outputs.tag }}
